### ISSUE TITLE
Closing windows doesn't seem to work

### ISSUE THREAD

**Issue by nspruit** [AirWM/AirWM#37]
Pressing super+w (which should close a window), does not work. I get the following error:

```
2015-01-06T15:15:43.372Z - info: Launching airwm-command: 'CloseWindow'.

/home/niels/Development/FP project/AirWM/lib/airwm.js:93
			closeWindowHandler(ev.child);
                      ^
ReferenceError: ev is not defined
    at /home/niels/Development/FP project/AirWM/lib/airwm.js:93:23
    at /home/niels/Development/FP project/AirWM/lib/airwm.js:135:6
    at XClient.<anonymous> (/home/niels/Development/FP project/AirWM/lib/airwm.js:172:3)
    at XClient.emit (events.js:67:17)
    at ReadFixedRequest.callback (/home/niels/Development/FP project/AirWM/node_modules/x11/lib/xcore.js:480:28)
    at ReadFixedRequest.execute (/home/niels/Development/FP project/AirWM/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/home/niels/Development/FP project/AirWM/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/home/niels/Development/FP project/AirWM/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/home/niels/Development/FP project/AirWM/node_modules/x11/lib/xcore.js:58:21)
    at Socket.emit (events.js:67:17)
    at Pipe.onread (net.js:347:14)

```

**Comment by harmjan** [comment]
Fixed in #46.
